In [1]:
# pip install yfinance

In [2]:
#Import Dependencies
import pip as np
import pandas as pd
import yfinance as yf
import plotly .graph_objs as go

from pathlib import Path
import numpy as np

from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from imblearn.ensemble import EasyEnsembleClassifier
from sklearn import preprocessing
from sklearn import utils
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

C:\Users\jemnj\.conda\envs\mlenv\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")


# DOGE-USD

In [3]:
ticker = yf.Ticker('DOGE-USD')
df2= ticker.history(period="5y")
df2.head()

Open      High       Low     Close   Volume  Dividends  \
Date                                                                     
2017-11-09  0.001207  0.001415  0.001181  0.001415  6259550          0   
2017-11-10  0.001421  0.001431  0.001125  0.001163  4246520          0   
2017-11-11  0.001146  0.001257  0.001141  0.001201  2231080          0   
2017-11-12  0.001189  0.001210  0.001002  0.001038  3288960          0   
2017-11-13  0.001046  0.001212  0.001019  0.001211  2481270          0   

            Stock Splits  
Date                      
2017-11-09             0  
2017-11-10             0  
2017-11-11             0  
2017-11-12             0  
2017-11-13             0

# BTC-USD

In [4]:
bitcoin_df = pd.read_csv("Resources/BTC-USD.csv")

In [5]:
bitcoin_df.head()

Date         Open         High          Low        Close      Volume  \
0  2017-08-22  3998.350098  4128.759766  3674.580078  4100.520020  3764239872   
1  2017-08-23  4089.010010  4255.779785  4078.409912  4151.520020  2369819904   
2  2017-08-24  4137.600098  4376.390137  4130.259766  4334.680176  2037750016   
3  2017-08-25  4332.819824  4455.700195  4307.350098  4371.600098  1727970048   
4  2017-08-26  4372.060059  4379.279785  4269.520020  4352.399902  1511609984   

   Dividends  Stock Splits  
0          0             0  
1          0             0  
2          0             0  
3          0             0  
4          0             0

# XRP-USD

In [6]:
ticker = yf.Ticker('DOGE-USD')
df3= ticker.history(period="5y")
df3.head()

Open      High       Low     Close   Volume  Dividends  \
Date                                                                     
2017-11-09  0.001207  0.001415  0.001181  0.001415  6259550          0   
2017-11-10  0.001421  0.001431  0.001125  0.001163  4246520          0   
2017-11-11  0.001146  0.001257  0.001141  0.001201  2231080          0   
2017-11-12  0.001189  0.001210  0.001002  0.001038  3288960          0   
2017-11-13  0.001046  0.001212  0.001019  0.001211  2481270          0   

            Stock Splits  
Date                      
2017-11-09             0  
2017-11-10             0  
2017-11-11             0  
2017-11-12             0  
2017-11-13             0

# Tether

In [7]:
ticker = yf.Ticker('USDT-USD')
df4= ticker.history(period="5y")
df4.head()

Open     High       Low    Close      Volume  Dividends  \
Date                                                                     
2017-11-09  1.01087  1.01327  0.996515  1.00818   358188000          0   
2017-11-10  1.00650  1.02423  0.995486  1.00601   756446016          0   
2017-11-11  1.00598  1.02621  0.995799  1.00899   746227968          0   
2017-11-12  1.00602  1.10591  0.967601  1.01247  1466060032          0   
2017-11-13  1.00448  1.02929  0.975103  1.00935   767884032          0   

            Stock Splits  
Date                      
2017-11-09             0  
2017-11-10             0  
2017-11-11             0  
2017-11-12             0  
2017-11-13             0

# Ethereum USD (ETH-USD)

In [8]:
ticker = yf.Ticker('ETH-USD')
df5= ticker.history(period="5y")
df5.head()

Open        High         Low       Close      Volume  \
Date                                                                     
2017-11-09  308.644989  329.451996  307.056000  320.884003   893249984   
2017-11-10  320.670990  324.717987  294.541992  299.252991   885985984   
2017-11-11  298.585999  319.453003  298.191986  314.681000   842300992   
2017-11-12  314.690002  319.153015  298.513000  307.907990  1613479936   
2017-11-13  307.024994  328.415009  307.024994  316.716003  1041889984   

            Dividends  Stock Splits  
Date                                 
2017-11-09          0             0  
2017-11-10          0             0  
2017-11-11          0             0  
2017-11-12          0             0  
2017-11-13          0             0

In [9]:
# Drop Unnecessary columns
X = df5.copy()
X = X.drop(columns=["Close","Volume","Dividends","Stock Splits"], axis=1)
X = pd.get_dummies(X)
X.head()

Open        High         Low
Date                                          
2017-11-09  308.644989  329.451996  307.056000
2017-11-10  320.670990  324.717987  294.541992
2017-11-11  298.585999  319.453003  298.191986
2017-11-12  314.690002  319.153015  298.513000
2017-11-13  307.024994  328.415009  307.024994

In [10]:
# Define the target set.
y = df5["Close"].ravel()
y[:5]

array([320.88400269, 299.25299072, 314.68099976, 307.9079895 ,
       316.71600342])

In [11]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [12]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [13]:
X_test_scaled

array([[ 1.67809337,  1.68988226,  1.7713079 ],
       [-0.49088546, -0.49996166, -0.48070823],
       [-0.78767817, -0.79310539, -0.78272682],
       ...,
       [-0.60757753, -0.61461316, -0.60853887],
       [ 2.42475501,  2.47727483,  2.45466003],
       [-0.06021584, -0.01843779, -0.0731147 ]])

In [14]:
X.describe()

Open         High          Low
count  1752.000000  1752.000000  1752.000000
mean   1113.227991  1149.985047  1071.403992
std    1228.539424  1266.220732  1184.883337
min      84.279694    85.342743    82.829887
25%     204.414921   210.575058   200.518307
50%     448.877335   465.586243   431.776596
75%    1837.357758  1894.583832  1776.323242
max    4810.071289  4891.704590  4718.039062

In [15]:
# Fitting the model
regr = RandomForestRegressor(max_depth=2, random_state=78)
regr.fit(X_train_scaled, y_train)

RandomForestRegressor(max_depth=2, random_state=78)

In [16]:
prediction=regr.predict(X_test_scaled)

In [17]:
regr.score(X_test_scaled,y_test)

0.9600967584935941

In [18]:
value_tocheck=[308.644989,329.451996, 307.056000]
scaledcheck= X_scaler.transform([value_tocheck])

C:\Users\jemnj\.conda\envs\mlenv\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [19]:
# Making predictions using the testing data.
print(regr.predict(scaledcheck))

[274.48487265]


In [20]:
# Calculate feature importance in the Random Forest model.
importances = regr.feature_importances_
importances

array([0.01833896, 0.22859156, 0.75306948])

In [21]:
X_test.columns

Index(['Open', 'High', 'Low'], dtype='object')